### ISSUE TITLE
./lanes.lua:327: can't copy non-deep full userdata across lanes

### ISSUE THREAD

**Issue by Phazeus** [LuaLanes/lanes#122]
Hello!
I has compile latest lanes yesterday from git.
I got error on creating new thread with lanes: "./lanes.lua:327: can't copy non-deep full userdata across lanes".
Error occured on string: "lanes.gen("*", client_function)(client)".
Here full code of script (lua 5.2):
-->>>>>>>>>
local lanes = require "lanes".configure()
local socket = require 'socket'
local server = socket.bind("*", 9000)
local function client_function(client)
  print("test1")
  client:send("I here")
  print("test2")
end
while true do
  local client = server:accept()
  client:send("hello")
  lanes.gen("*", client_function)(client)
end
--<<<<<<<<<<

WIth "local lanes = require "lanes".configure({demote_full_userdata = true})" no such error, but it does not works. When I trying to work with "client" object, threads just doing nothing.
I see:
hello
test1
And I don't see "I here" and "test2". Program just freezing.
Thanks.

**Comment by sonoro1234** [comment]
Seems #107

**Comment by benoit-germain** [comment]
Well yes, the only full userdata that Lanes can copy across states must be 'deep' userdata. You can see such an object as a smart pointer to the actual userdata. The userdata itself is not duplicated, only the smart pointer, with proper reference counting. This is because Lanes can't know how to properly duplicate all userdata objects that third-party libraries may expose. So, anytime such a userdata is encountered, either in a lane's function, or in data sent through a linda, you'll get this error from Lanes. The only solution is to change the code so that the value is not sent. Usually this means avoiding functions referencing such objects by upvalue. In the case of luasockets, this means you can't send a socket across lanes. You have to make you lanes create the socket. But of course, this means a socket can't be shared by different lanes. The only solution for that is to have LuaSocket make their userdata 'deep' so that they can operate with Lanes (with proper mutex locking of course, as this would mean that a given socket can potentially be accessed concurrently from several threads).
