### ISSUE TITLE
Issue with globals

### ISSUE THREAD

**Issue by kumpuu** [LuaLanes/lanes#128]
Hi, I'm trying to embed this lib into my application. 
I've gotten so far as being able to generate and call lanes. However it does not seem to copy any functions or globals which lane_func uses over to the new lane. I'm not sure if this is intended behaviour or if I'm just doing it wrong.

Example for what I mean:

function foo()
	return "success"
end

function lane_func()
	print(foo()) --does not work
end

lanes = require "lanes".configure()
a = lanes.gen("*", lane_func)
a()

The documentation says:

> Lanes automatically copies upvalues over to the new lanes, so you need not wrap all the required elements into one 'wrapper' function. If lane_func uses some local values, or local functions, they will be there also in the new lanes.

So it only copies them if they have the local keyword, yes? It's not very clear about how to handle globals. Or I'm just too stupid to understand it :)
So whats the proper way to do this? Do i have to declare everything again in opt_tbl's globals?

**Comment by benoit-germain** [comment]
Well, you got this right: As such, function lane_func doesn't actually reference function foo, it just performs a lookup for key "foo" in the global space, then 'calls' whatever it got. If it happens the value is a function, then the function is called. When this lane_func is sent over a lane, there is no actual reference to function foo sent as well, so in your lane, the lookup just retrieves nil, and attempting to call nil raises an error.
So yes, you have either to make foo local, so that it is an upvalue of lane_func, or you have to send it over your lane through opt_tbl.globals.
