### ISSUE TITLE
Publish 3.14 on LuaRocks ?

### ISSUE THREAD

**Issue by jperon** [LuaLanes/lanes#180]
Hello,

When using v.3.13 (installed by default when running `luarocks install lanes`) with LuaJit, I get the infamous #147. Manually installing master version fixed the problem ; so I wondered whether it would be possible to publish it, which would avoid the problem for anyone !

Many thanks for all the great job !

**Comment by MikeWent** [comment]
It would be awesome, I agree.

**Comment by CAOakleyII** [comment]
@jperon  Which version of LuaJit are you using, I was unable to fix the "bad light userdata pointer" error when compiling from latest in source.

I'm currently testing with LuaJIT 2.1.0-beta3 (from 2017).

**Comment by jperon** [comment]
I'm using LuaJit 2.1.0-beta3, as found on Arch Linux. I cloned lanes, fixed `cancel.c` as in #185, run `make` and `make install`, and it worked (without having to go back in the history). Here is the output of `luajit -v`:

```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
```

**Comment by CAOakleyII** [comment]
Thanks, that's exactly what I did (including the cancel.c issue), however it looks like your previous [post ](https://github.com/LuaLanes/lanes/issues/180#issue-604550895) about it working was made just an hour before [these latest commits](https://github.com/LuaLanes/lanes/commit/237c642fb50ee0d4c777fc9cd0e7a5b0ead7cabd) to master. It seems, the latest master version does not work, since then.


Thanks for confirming all the other info though!

**Comment by jperon** [comment]
Just to confirm: I tested again before reply (I had changed my system since the first post), so in my case, latest master does work.

**Comment by benoit-germain** [comment]
Just uploaded rockspec for 3.15.0.
