### ISSUE TITLE
Problems on macOSX

### ISSUE THREAD

**Issue by stevewi-niteflyte** [LuaLanes/lanes#230]
I built *lanes* with *luarocks* v3.11.1.  I read the release notes wrt building on macOS and dynamic libraries, etc.  As far as I can tell, *lua* and *lanes*, are built correctly (my *luaconf.h* is attached).  I used *clang* (the macOS native C/C++ compiler) to do all the builds:
```
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: x86_64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
The macOS version information is:

**Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:49 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_X86_64 x86_64**

(this is *macOS Sonoma v14.7.1 (23H222)*).

I have the following Lua program:
```
lanes = require("lanes")
print("hello world")
```

When I run this program:  `lua demo.lua`
I get the following:
```
lua: error loading module 'lanes.core' from file '/Users/stevewi/usr/lib/lua/5.4/lanes/core.dylib':
	dlopen(/Users/stevewi/usr/lib/lua/5.4/lanes/core.dylib, 0x0006): symbol not found in flat namespace '_STACK_GROW'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/Users/stevewi/usr/share/lua/5.4/lanes.lua:38: in main chunk
	[C]: in function 'require'
	demo.lua:1: in main chunk
	[C]: in ?
```
(as far as I can tell, *LUA_PATH* & *LUA_CPATH* are set correctly).

When I examine *core.dylib*, I do indeed see an undefined symbol:

```
stevewi:~ $ nm /Users/stevewi/usr/lib/lua/5.4/lanes/core.dylib | grep STACK_GROW
                 U _STACK_GROW
```

When I look at your source code, I find the function:

`inline void STACK_GROW(lua_State* L_, int n_)`

in the file *src/macros_and_utils.hpp*.

My best guess is that this undefined symbol is due to a compiler quirk that is optimizing the symbol `STACK_GROW` out of existence because of the *inline* declaration.

Is there any way I can get around this?  I'm relatively new to Lua but I have LOTS of programming experience.  Thanks in advance...

[luaconf.h.txt](https://github.com/user-attachments/files/17723360/luaconf.h.txt)

**Comment by benoit-germain** [comment]
I just don't get why this issue shows up. STACK_GROW is used internally, and isn't supposed to be visible outside the lanes module itself. If in some places the compiler decided to do a non-inline call to the function, but somehow forgot to embed an instanciation of said function in the text, I don't see what I can do about it.

That being said, I have 0 experience with MacOS development, so I asked Copilot for its thoughts on the issue :-). Here is the result after pasting your original question verbatim, but you'll have to test that yourself. 

-- COPILOT TRANSCRIPT BEGIN
It sounds like you’ve done a thorough job setting up your environment and identifying the issue. The problem you’re encountering with the undefined symbol _STACK_GROW might indeed be related to how the compiler handles inline functions. Here are a few steps you can try to resolve this:

Ensure Proper Exporting of Symbols: Make sure that the STACK_GROW function is properly exported. You can try adding an extern declaration to ensure the symbol is visible across translation units. For example, in macros_and_utils.hpp, you can modify the function declaration like this:
extern inline void STACK_GROW(lua_State* L_, int n_);

Disable Inlining: If the issue is due to the compiler optimizing out the inline function, you can try disabling inlining for this specific function. You can remove the inline keyword or use compiler-specific attributes to prevent inlining. For example:
void STACK_GROW(lua_State* L_, int n_)
{
    if (!lua_checkstack(L_, n_)) {
        raise_luaL_error(L_, "Cannot grow stack!");
    }
}

Check Compiler Flags: Ensure that you are using the correct compiler flags that might affect symbol visibility. For example, using -fvisibility=default can help ensure that all symbols are exported by default.
Rebuild the Module: After making these changes, clean and rebuild the lanes module to ensure that the changes take effect.
Dynamic Library Path: Double-check that the dynamic library path is correctly set and that there are no conflicting versions of the library. You can use otool -L /Users/stevewi/usr/lib/lua/5.4/lanes/core.dylib to inspect the dependencies of the dynamic library.
If these steps don’t resolve the issue, you might want to reach out to the maintainers of the lanes library or check if there are any known issues with the specific version of luarocks and lanes you are using.

Feel free to ask if you need further assistance or clarification on any of these steps!
-- COPILOT TRANSCRIPT END

**Comment by stevewi-niteflyte** [comment]
Thanks for your response.  All of the COPILOT stuff just confirms my suspicion that it's a compiler issue.  That being said, I downloaded your code and did some environment-variable/Makefile tricks to simulate building a *luarock* and hand-built your shared library.   I got the problem I reported to go away.

I discovered a number of things...  I'll just list the salient ones here:

- **_-O2_** optimization is the ultimate culprit for the problem I reported.  It's optimizing the symbol *STACK_GROW* out of existence because *STACK_GROW* is an *inline* function.  The simplest solution is to disable **_-O2_** in the build.
- During linking, I got this:
```
MACOSX_DEPLOYMENT_TARGET=10.3 gcc -bundle -undefined dynamic_lookup _pch.o cancel.o compat.o deep.o intercopycontext.o keeper.o lane.o lanes.o linda.o lindafactory.o nameof.o state.o threading.o tools.o tracker.o universe.o -L/usr/local/lib -llua -lm -L/usr/local/lib -llua -lm -o lanes/core.so
ld: warning: support for macOS with 10.3 minimum deployment target is deprecated and will be removed in a future release
ld: warning: ld: warning: ld: warning: object file (compat.o) was built for newer macOS version (14.0) than being linked (10.3)ld: warning: object file (_pch.o) was built for newer macOS version (14.0) than being linked (10.3)
```
The *Makefile* variable **MACOSX_DEPLOYMENT_TARGET** is probably part of the *Makefile* boilerplate the *luarocks* folks gave you for packaging *lanes* as a *luarock*.

This indicates a serious problem with *luarocks* packaging.  macOS 10.3 only ran on the PowerPC.  Apple hasn't produced any PowerPC machines for **_at least_** 10 years.  My only conclusion is that the *luarocks* team doesn't have a macOS expert or whoever their "expert" is hasn't kept up with the times.  I suspect that the problem is some of both...

I can easily fix both of these for you for *lanes* but that doesn't solve the deeper *luarocks* packaging issues.  These are much more widespread and (I suspect) that neither one of us wants to go to the mattresses about them.  That being said, until **_THOSE_** problems get addressed, Lua will nevert be ready for prime time as a development choice on macOS.  It certainly won't be suitable for what I want to do.

Thanks for your time and consideration.  I'm glad I discovered this before I had invested a lot of time and effort in Lua.
